import { CardTypeConfig } from '@/types';

export const CARD_TYPES: CardTypeConfig[] = [
  {
    id: 'creature',
    label: 'Creature',
    description: 'Random creature at selected CMC',
    multiCard: false,
    useCmc: true,
    count: 1,
  },
  {
    id: 'commander',
    label: 'Commander',
    description: 'Random legendary creature commander',
    multiCard: false,
    useCmc: true,
    count: 1,
  },
  {
    id: 'artifact',
    label: 'Artifact',
    description: 'Random artifact at selected CMC',
    multiCard: false,
    useCmc: true,
    count: 1,
  },
  {
    id: 'equipment',
    label: 'Equipment',
    description: 'Random equipment at selected CMC',
    multiCard: false,
    useCmc: true,
    count: 1,
  },
  {
    id: 'enchantment',
    label: 'Enchantment',
    description: 'Random enchantment at selected CMC',
    multiCard: false,
    useCmc: true,
    count: 1,
  },
  {
    id: 'aura',
    label: 'Aura',
    description: 'Random aura at selected CMC',
    multiCard: false,
    useCmc: true,
    count: 1,
  },
  {
    id: 'instants',
    label: '5 Random Instants',
    description: '5 random instants (no CMC filter)',
    multiCard: true,
    useCmc: false,
    count: 5,
  },
  {
    id: 'sorceries',
    label: '5 Random Sorceries',
    description: '5 random sorceries (no CMC filter)',
    multiCard: true,
    useCmc: false,
    count: 5,
  },
  {
    id: 'lands',
    label: '5 Random Lands',
    description: '5 random non-basic lands (no CMC filter)',
    multiCard: true,
    useCmc: false,
    count: 5,
  },
];
