import { StyleSheet } from 'react-native';

import Colors from '@/constants/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  bgWrap: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  bgImageWrap: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '68%',
  },
  bgImage: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  safeAreaCover: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 2,
  },
  bgGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  bgBottomFill: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: '40%',
  },
  innerContainer: {
    flex: 1,
  },
  sessionBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    marginHorizontal: 20,
    backgroundColor: 'rgba(232,105,45,0.15)',
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(232,105,45,0.3)',
  },
  sessionText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '600' as const,
  },
  spacer: {
    flex: 1,
  },
  bottomControls: {
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  typeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    marginBottom: 12,
    marginTop: 24,
  },
  typeLabelWrap: {
    flex: 1,
    alignItems: 'center',
    paddingHorizontal: 12,
  },
  typeLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  typeSelectorText: {
    fontSize: 16,
    color: Colors.textPrimary,
    fontWeight: '600' as const,
  },
  typeDescription: {
    fontSize: 11,
    color: Colors.textSecondary,
    marginTop: 2,
  },
  typeIndicatorRow: {
    flexDirection: 'row',
    gap: 5,
    justifyContent: 'center',
    marginBottom: 18,
  },
  typeIndicatorDot: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: 'rgba(232,105,45,0.18)',
  },
  typeIndicatorDotActive: {
    backgroundColor: Colors.gold,
    width: 16,
    borderRadius: 3,
  },
  cmcSection: {
    width: '100%',
    marginBottom: 20,
  },
  cmcHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
    gap: 24,
  },
  cmcStepButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(232,105,45,0.1)',
    borderWidth: 1.5,
    borderColor: 'rgba(232,105,45,0.25)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cmcStepButtonPressed: {
    backgroundColor: 'rgba(232,105,45,0.25)',
    borderColor: Colors.gold,
  },
  cmcStepButtonDisabled: {
    opacity: 0.3,
  },
  cmcDisplay: {
    alignItems: 'center',
    minWidth: 80,
  },
  cmcValue: {
    fontSize: 52,
    fontWeight: '200' as const,
    color: Colors.gold,
    lineHeight: 58,
  },
  cmcLabel: {
    fontSize: 9,
    fontWeight: '700' as const,
    color: 'rgba(232,105,45,0.45)',
    letterSpacing: 4,
    marginTop: 2,
  },
  multiCardSection: {
    alignItems: 'center',
    gap: 10,
    paddingVertical: 14,
    marginBottom: 18,
  },
  multiCardLabel: {
    fontSize: 14,
    color: Colors.textSecondary,
    fontWeight: '500' as const,
  },
  castButtonWrap: {
    width: '100%',
    alignItems: 'center',
    marginBottom: 10,
  },
  castButton: {
    backgroundColor: Colors.gold,
    paddingVertical: 10,
    paddingHorizontal: 36,
    borderRadius: 12,
    minWidth: 140,
    alignItems: 'center',
    shadowColor: '#E8692D',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 6,
  },
  castButtonPressed: {
    backgroundColor: Colors.goldDark,
  },
  castButtonDisabled: {
    opacity: 0.7,
  },
  castButtonText: {
    fontSize: 14,
    fontWeight: '700' as const,
    color: '#fff',
    letterSpacing: 0,
  },
  errorContainer: {
    backgroundColor: 'rgba(255,68,68,0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255,68,68,0.3)',
    borderRadius: 12,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    width: '100%',
    marginBottom: 10,
  },
  errorText: {
    color: Colors.error,
    fontSize: 13,
    flex: 1,
  },
  retryButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: 'rgba(255,68,68,0.2)',
  },
  retryText: {
    color: Colors.error,
    fontSize: 12,
    fontWeight: '600' as const,
  },
  historyButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 20,
    backgroundColor: 'rgba(0,0,0,0.35)',
    borderWidth: 1,
    borderColor: 'rgba(232,105,45,0.15)',
    marginTop: 4,
  },
  historyButtonPressed: {
    backgroundColor: 'rgba(232,105,45,0.15)',
    borderColor: 'rgba(232,105,45,0.3)',
  },
  historyButtonLabel: {
    fontSize: 13,
    fontWeight: '600' as const,
    color: Colors.gold,
  },
  historyBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    backgroundColor: Colors.gold,
    borderRadius: 9,
    minWidth: 18,
    height: 18,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 4,
  },
  historyBadgeText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '700' as const,
  },
});
