import { StyleSheet, Dimensions } from 'react-native';
import Colors from '@/constants/colors';

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');

export { SCREEN_WIDTH, SCREEN_HEIGHT };

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  scrollContent: {
    flex: 1,
  },
  scrollInner: {
    paddingBottom: 16,
  },
  heroBanner: {
    width: '100%',
    position: 'relative' as const,
    overflow: 'hidden',
  },
  safeAreaCover: {
    position: 'absolute' as const,
    top: 0,
    left: 0,
    right: 0,
    zIndex: 5,
  },
  heroImageWrap: {
    width: '100%',
    height: '100%',
  },
  heroImage: {
    width: '100%',
    height: '100%',
  },
  heroGradient: {
    position: 'absolute' as const,
    left: 0,
    right: 0,
    bottom: 0,
  },
  topBar: {
    position: 'absolute' as const,
    top: 0,
    left: 0,
    right: 0,
    flexDirection: 'row' as const,
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    zIndex: 10,
  },
  topBarButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
  },
  pageChip: {
    backgroundColor: 'rgba(0,0,0,0.45)',
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 12,
  },
  pageChipText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '600' as const,
  },
  heroContent: {
    position: 'absolute' as const,
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 16,
    paddingBottom: 14,
    zIndex: 10,
    gap: 6,
  },
  cardName: {
    fontSize: 28,
    fontWeight: '800' as const,
    color: '#ffffff',
    lineHeight: 33,
    textShadowColor: 'rgba(0,0,0,0.9)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 12,
  },
  body: {
    paddingHorizontal: 16,
    paddingTop: 12,
    gap: 10,
  },
  typeAndPtRow: {
    flexDirection: 'row' as const,
    gap: 8,
    alignItems: 'stretch',
  },
  typeCard: {
    flex: 1,
    backgroundColor: Colors.cardBackground,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.border,
    paddingHorizontal: 16,
    paddingVertical: 12,
    justifyContent: 'center' as const,
  },
  typeCardWithPt: {
    alignItems: 'flex-start' as const,
  },
  typeCardText: {
    color: Colors.textPrimary,
    fontSize: 14,
    fontWeight: '600' as const,
  },
  ptCompactCard: {
    flexDirection: 'row' as const,
    alignItems: 'center',
    backgroundColor: 'rgba(232,105,45,0.08)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(232,105,45,0.2)',
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 8,
    minWidth: 100,
  },
  ptIconRow: {
    flexDirection: 'row' as const,
    alignItems: 'center',
    gap: 4,
  },
  ptCompactValue: {
    color: Colors.gold,
    fontSize: 18,
    fontWeight: '900' as const,
  },
  ptDivider: {
    width: 1,
    height: 18,
    backgroundColor: 'rgba(232,105,45,0.25)',
  },
  oracleSection: {
    backgroundColor: Colors.cardBackground,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Colors.border,
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  flavorSection: {
    backgroundColor: 'rgba(232,105,45,0.04)',
    borderRadius: 12,
    borderLeftWidth: 3,
    borderLeftColor: 'rgba(232,105,45,0.3)',
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  flavorText: {
    color: Colors.textSecondary,
    fontSize: 13,
    fontStyle: 'italic' as const,
    lineHeight: 20,
  },
  detailsCard: {
    backgroundColor: Colors.cardBackground,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Colors.border,
    overflow: 'hidden' as const,
  },
  sectionHeaderRow: {
    flexDirection: 'row' as const,
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 4,
  },
  sectionHeaderText: {
    color: Colors.gold,
    fontSize: 11,
    fontWeight: '700' as const,
    textTransform: 'uppercase' as const,
    letterSpacing: 0.5,
  },
  detailGrid: {
    paddingHorizontal: 16,
    paddingBottom: 14,
    paddingTop: 6,
  },
  detailItem: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Colors.border,
  },
  detailItemLast: {
    borderBottomWidth: 0,
  },
  detailLabel: {
    color: Colors.textMuted,
    fontSize: 13,
    fontWeight: '500' as const,
    minWidth: 70,
  },
  detailValue: {
    color: Colors.textPrimary,
    fontSize: 14,
    fontWeight: '600' as const,
    flexShrink: 1,
  },
  detailValueRow: {
    flexDirection: 'row' as const,
    alignItems: 'center',
    gap: 5,
    flexShrink: 1,
  },
  detailMeta: {
    color: Colors.textMuted,
    fontSize: 11,
    fontWeight: '500' as const,
    backgroundColor: 'rgba(255,255,255,0.06)',
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: 3,
    overflow: 'hidden' as const,
  },
  rarityDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  navRow: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between',
    gap: 10,
  },
  navButton: {
    flex: 1,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    gap: 5,
    backgroundColor: Colors.cardBackground,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  navDisabled: {
    opacity: 0.35,
  },
  navText: {
    color: Colors.gold,
    fontSize: 14,
    fontWeight: '600' as const,
  },
  navTextDisabled: {
    color: Colors.textMuted,
  },
  actions: {
    flexDirection: 'row' as const,
    gap: 10,
    paddingHorizontal: 16,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
    backgroundColor: Colors.background,
  },
  actionBtn: {
    flex: 1,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    gap: 6,
    paddingVertical: 13,
    borderRadius: 12,
  },
  actionPressed: {
    opacity: 0.75,
  },
  actionOutline: {
    backgroundColor: Colors.cardBackground,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  actionOutlineText: {
    color: Colors.gold,
    fontSize: 13,
    fontWeight: '700' as const,
  },
  actionPrimary: {
    backgroundColor: Colors.gold,
  },
  actionPrimaryText: {
    color: Colors.background,
    fontSize: 13,
    fontWeight: '700' as const,
  },
  errorState: {
    flex: 1,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    gap: 16,
  },
  errorText: {
    color: Colors.textSecondary,
    fontSize: 16,
  },
  backBtn: {
    backgroundColor: Colors.gold,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 12,
  },
  backBtnText: {
    color: Colors.background,
    fontSize: 14,
    fontWeight: '700' as const,
  },
  modalWrap: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.95)',
  },
  modalContent: {
    flex: 1,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    paddingHorizontal: 24,
  },
  modalImage: {
    width: SCREEN_WIDTH - 64,
    height: (SCREEN_WIDTH - 64) * 1.395,
    borderRadius: 14,
    maxHeight: SCREEN_HEIGHT * 0.68,
  },
  modalClose: {
    position: 'absolute' as const,
    right: 20,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.12)',
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
  },
  modalFooter: {
    marginTop: 20,
    alignItems: 'center' as const,
    gap: 4,
    paddingHorizontal: 16,
  },
  modalName: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '700' as const,
    textAlign: 'center' as const,
  },
  modalMeta: {
    color: 'rgba(255,255,255,0.45)',
    fontSize: 13,
    textAlign: 'center' as const,
    lineHeight: 18,
  },
  artModalWrap: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.97)',
  },
  artModalContent: {
    flex: 1,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    paddingHorizontal: 16,
  },
  artModalImage: {
    width: SCREEN_WIDTH - 32,
    height: (SCREEN_WIDTH - 32) * 0.73,
    borderRadius: 10,
  },
  artModalClose: {
    position: 'absolute' as const,
    right: 20,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.12)',
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
  },
  artModalFooter: {
    marginTop: 24,
    alignItems: 'center' as const,
    gap: 6,
  },
  artModalTitle: {
    color: '#fff',
    fontSize: 20,
    fontWeight: '700' as const,
    textAlign: 'center' as const,
  },
  artModalArtist: {
    color: 'rgba(255,255,255,0.5)',
    fontSize: 14,
    textAlign: 'center' as const,
  },
  artModalActions: {
    flexDirection: 'row' as const,
    gap: 16,
    marginTop: 16,
  },
  artModalBtn: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 8,
    backgroundColor: 'rgba(255,255,255,0.1)',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 12,
  },
  artModalBtnText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600' as const,
  },
  printingsHeader: {
    flexDirection: 'row' as const,
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: Colors.cardBackground,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Colors.border,
    paddingRight: 14,
  },
  printingsCountBadge: {
    backgroundColor: 'rgba(232,105,45,0.15)',
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 8,
    marginLeft: 4,
  },
  printingsCountText: {
    color: Colors.gold,
    fontSize: 10,
    fontWeight: '700' as const,
  },
  printingsList: {
    backgroundColor: Colors.cardBackground,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Colors.border,
    overflow: 'hidden' as const,
    marginTop: -4,
  },
  printingsLoadingWrap: {
    flexDirection: 'row' as const,
    alignItems: 'center',
    justifyContent: 'center' as const,
    gap: 10,
    paddingVertical: 20,
  },
  printingsLoadingText: {
    color: Colors.textMuted,
    fontSize: 13,
  },
  printingItem: {
    flexDirection: 'row' as const,
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 11,
    gap: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Colors.border,
  },
  printingItemCurrent: {
    backgroundColor: 'rgba(232,105,45,0.06)',
  },
  printingRarityDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
  },
  printingInfo: {
    flex: 1,
    gap: 2,
  },
  printingSetName: {
    color: Colors.textPrimary,
    fontSize: 13,
    fontWeight: '600' as const,
  },
  printingSetNameCurrent: {
    color: Colors.gold,
  },
  printingMeta: {
    color: Colors.textMuted,
    fontSize: 11,
  },
  printingRarityLabel: {
    fontSize: 12,
    fontWeight: '800' as const,
    width: 18,
    textAlign: 'center' as const,
  },
});
