import { StyleSheet } from 'react-native';
import Colors from '@/constants/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#080a0f',
  },
  twoPlayerLayout: {
    flex: 1,
    flexDirection: 'column',
  },
  fourPlayerLayout: {
    flex: 1,
    flexDirection: 'column',
  },
  fourPlayerRow: {
    flex: 1,
    flexDirection: 'row',
  },
  fourPlayerCell: {
    flex: 1,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.06)',
  },
  divider: {
    height: 52,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 16,
    backgroundColor: '#0a0c11',
    zIndex: 10,
  },
  fourPlayerDivider: {
    height: 52,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    backgroundColor: '#0a0c11',
    zIndex: 10,
  },
  modeIndicator: {
    paddingHorizontal: 14,
    paddingVertical: 5,
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  modeText: {
    color: 'rgba(255,255,255,0.45)',
    fontSize: 11,
    fontWeight: '600' as const,
    letterSpacing: 1,
    textTransform: 'uppercase' as const,
  },
  modeTextSmall: {
    color: 'rgba(255,255,255,0.45)',
    fontSize: 10,
    fontWeight: '600' as const,
    letterSpacing: 1,
    textTransform: 'uppercase' as const,
  },
  centerButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(255,255,255,0.04)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  castButton: {
    width: 'auto',
    minWidth: 38,
    paddingHorizontal: 12,
    flexDirection: 'row',
    gap: 6,
    backgroundColor: Colors.gold,
  },
  castButtonSmall: {
    paddingHorizontal: 10,
  },
  castButtonDisabled: {
    backgroundColor: Colors.goldLight,
  },
  castButtonText: {
    color: Colors.background,
    fontSize: 11,
    fontWeight: '800' as const,
    letterSpacing: 0.6,
    textTransform: 'uppercase' as const,
  },
  castButtonTextSmall: {
    fontSize: 10,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.8)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  counterPickerSheet: {
    backgroundColor: '#161820',
    borderRadius: 20,
    padding: 22,
    width: '80%',
    maxWidth: 340,
    gap: 6,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
  },
  pickerTitle: {
    color: '#e8e8e8',
    fontSize: 17,
    fontWeight: '700' as const,
    textAlign: 'center' as const,
  },
  pickerSubtitle: {
    color: Colors.textSecondary,
    fontSize: 13,
    textAlign: 'center' as const,
    marginBottom: 10,
  },
  cmcGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 8,
  },
  cmcOption: {
    width: 52,
    height: 44,
    borderRadius: 12,
    backgroundColor: Colors.cardBackgroundLight,
    borderWidth: 1,
    borderColor: `${Colors.gold}22`,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cmcOptionText: {
    color: Colors.textPrimary,
    fontSize: 16,
    fontWeight: '700' as const,
  },
  counterOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.03)',
    borderWidth: 1,
    borderColor: 'transparent',
  },
  counterIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  counterOptionText: {
    fontSize: 15,
    fontWeight: '500' as const,
    flex: 1,
    color: '#aaa',
  },
  activeDot: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
  },
  settingsSheet: {
    backgroundColor: '#161820',
    borderRadius: 22,
    padding: 24,
    width: '88%',
    maxWidth: 400,
    gap: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
  },
  settingsTitle: {
    color: '#e8e8e8',
    fontSize: 19,
    fontWeight: '800' as const,
    textAlign: 'center' as const,
    marginBottom: 6,
  },
  settingLabel: {
    color: 'rgba(255,255,255,0.4)',
    fontSize: 11,
    fontWeight: '600' as const,
    letterSpacing: 1.5,
    textTransform: 'uppercase' as const,
  },
  optionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  optionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
  },
  optionButtonActive: {
    backgroundColor: '#e8e8e8',
    borderColor: '#e8e8e8',
  },
  optionText: {
    color: '#aaa',
    fontSize: 14,
    fontWeight: '600' as const,
  },
  optionTextActive: {
    color: '#111',
  },
  resetAllButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 13,
    borderRadius: 12,
    backgroundColor: 'rgba(255,107,107,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255,107,107,0.2)',
  },
  resetAllText: {
    color: '#ff6b6b',
    fontSize: 14,
    fontWeight: '600' as const,
  },
  doneButton: {
    alignItems: 'center',
    paddingVertical: 13,
    borderRadius: 12,
    backgroundColor: '#e8e8e8',
  },
  doneButtonText: {
    color: '#111',
    fontSize: 15,
    fontWeight: '700' as const,
  },
});
