import { StyleSheet } from 'react-native';
import Colors from '@/constants/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 4,
    paddingBottom: 14,
  },
  backButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: Colors.cardBackground,
    justifyContent: 'center',
    alignItems: 'center',
  },
  title: {
    fontSize: 17,
    fontWeight: '700' as const,
    color: Colors.gold,
    letterSpacing: 0.3,
  },
  scrollContent: {
    flex: 1,
    paddingHorizontal: 16,
  },
  errorCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    backgroundColor: 'rgba(239,83,80,0.08)',
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: 'rgba(239,83,80,0.2)',
    marginBottom: 12,
  },
  errorCardText: {
    color: Colors.error,
    fontSize: 13,
    lineHeight: 18,
    flex: 1,
  },
  permissionDeniedCard: {
    backgroundColor: 'rgba(239,83,80,0.08)',
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(239,83,80,0.3)',
    marginBottom: 12,
  },
  permissionDeniedHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  permissionDeniedTitle: {
    color: Colors.error,
    fontSize: 14,
    fontWeight: '700' as const,
  },
  permissionDeniedText: {
    color: Colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
    marginBottom: 14,
  },
  permissionDeniedButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: Colors.error,
    paddingVertical: 10,
    borderRadius: 10,
  },
  permissionDeniedButtonPressed: {
    opacity: 0.85,
  },
  permissionDeniedButtonText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '700' as const,
  },
  unsupportedCard: {
    backgroundColor: 'rgba(232,105,45,0.08)',
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(232,105,45,0.3)',
    marginBottom: 12,
  },
  unsupportedHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  unsupportedTitle: {
    color: Colors.gold,
    fontSize: 14,
    fontWeight: '700' as const,
  },
  unsupportedText: {
    color: Colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
    marginBottom: 14,
  },
  unsupportedButton: {
    backgroundColor: 'rgba(232,105,45,0.15)',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignSelf: 'flex-start',
  },
  unsupportedButtonPressed: {
    opacity: 0.8,
  },
  unsupportedButtonText: {
    color: Colors.gold,
    fontSize: 13,
    fontWeight: '600' as const,
  },
  disconnectedCard: {
    backgroundColor: 'rgba(239,83,80,0.08)',
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(239,83,80,0.25)',
    marginBottom: 12,
  },
  disconnectedHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  disconnectedTitle: {
    color: Colors.error,
    fontSize: 14,
    fontWeight: '700' as const,
  },
  disconnectedText: {
    color: Colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
    marginBottom: 14,
  },
  disconnectedActions: {
    flexDirection: 'row',
    gap: 10,
  },
  disconnectedButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: 'rgba(232,105,45,0.12)',
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(232,105,45,0.25)',
  },
  disconnectedButtonPressed: {
    opacity: 0.8,
  },
  disconnectedButtonText: {
    color: Colors.gold,
    fontSize: 13,
    fontWeight: '600' as const,
  },
  disconnectedButtonSecondary: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: Colors.cardBackground,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  disconnectedButtonSecondaryPressed: {
    opacity: 0.8,
  },
  disconnectedButtonSecondaryText: {
    color: Colors.textSecondary,
    fontSize: 13,
    fontWeight: '600' as const,
  },
  connectingCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: 'rgba(232,105,45,0.08)',
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(232,105,45,0.25)',
    marginBottom: 12,
  },
  connectingText: {
    color: Colors.gold,
    fontSize: 13,
    fontWeight: '600' as const,
  },
  uncertainCard: {
    backgroundColor: 'rgba(232,105,45,0.08)',
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(232,105,45,0.3)',
    marginBottom: 12,
  },
  uncertainHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  uncertainTitle: {
    color: Colors.gold,
    fontSize: 14,
    fontWeight: '700' as const,
  },
  uncertainText: {
    color: Colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
    marginBottom: 12,
  },
  uncertainJobList: {
    gap: 8,
  },
  uncertainJobItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(232,105,45,0.08)',
    borderRadius: 8,
    padding: 10,
    gap: 10,
  },
  uncertainJobInfo: {
    flex: 1,
  },
  uncertainJobType: {
    fontSize: 12,
    fontWeight: '600' as const,
    color: Colors.textPrimary,
  },
  uncertainJobError: {
    fontSize: 11,
    color: Colors.textSecondary,
    marginTop: 2,
  },
  uncertainJobActions: {
    flexDirection: 'row',
    gap: 6,
  },
  uncertainRetryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: Colors.gold,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
  },
  uncertainRetryText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '700' as const,
  },
  uncertainAbandonButton: {
    backgroundColor: 'rgba(239,83,80,0.15)',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
  },
  uncertainAbandonText: {
    color: Colors.error,
    fontSize: 11,
    fontWeight: '700' as const,
  },
  connectedCard: {
    backgroundColor: Colors.cardBackground,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(34,204,102,0.25)',
    marginBottom: 20,
  },
  connectedHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  connectedIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: Colors.success,
    justifyContent: 'center',
    alignItems: 'center',
  },
  connectedInfo: {
    flex: 1,
  },
  connectedName: {
    color: Colors.textPrimary,
    fontSize: 16,
    fontWeight: '700' as const,
  },
  connectedMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 3,
  },
  connectedTypeBadge: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  connectedAddress: {
    color: Colors.textMuted,
    fontSize: 11,
  },
  connectedCanonical: {
    color: Colors.textMuted,
    fontSize: 10,
    marginTop: 2,
    fontStyle: 'italic' as const,
  },
  connectedDivider: {
    height: 1,
    backgroundColor: Colors.border,
    marginVertical: 12,
  },
  connectedActions: {
    flexDirection: 'row',
    gap: 10,
  },
  testButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: 'rgba(232,105,45,0.08)',
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(232,105,45,0.2)',
  },
  testButtonPressed: {
    opacity: 0.85,
  },
  testButtonText: {
    color: Colors.gold,
    fontSize: 13,
    fontWeight: '600' as const,
  },
  disconnectButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,68,68,0.08)',
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,68,68,0.2)',
  },
  disconnectButtonPressed: {
    opacity: 0.85,
  },
  disconnectText: {
    color: Colors.error,
    fontSize: 13,
    fontWeight: '600' as const,
  },
  queueReconcileCard: {
    backgroundColor: Colors.cardBackground,
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: Colors.border,
    marginBottom: 16,
  },
  queueReconcileHeader: {
    marginBottom: 12,
  },
  queueReconcileTitle: {
    color: Colors.textPrimary,
    fontSize: 14,
    fontWeight: '700' as const,
  },
  queueReconcileSection: {
    marginBottom: 12,
  },
  queueReconcileSectionLabel: {
    color: Colors.gold,
    fontSize: 11,
    fontWeight: '700' as const,
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  queueReconcileJob: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFBF0',
    borderRadius: 8,
    padding: 8,
    gap: 8,
    marginBottom: 6,
  },
  queueReconcileJobInfo: {
    flex: 1,
  },
  queueReconcileJobType: {
    fontSize: 12,
    fontWeight: '600' as const,
    color: Colors.textPrimary,
  },
  queueReconcileJobError: {
    fontSize: 10,
    color: Colors.textSecondary,
    marginTop: 1,
  },
  queueReconcileRetry: {
    backgroundColor: Colors.gold,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 6,
  },
  queueReconcileRetryText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '700' as const,
  },
  queueReconcileAbandon: {
    backgroundColor: 'rgba(239,83,80,0.15)',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 6,
  },
  queueReconcileAbandonText: {
    color: Colors.error,
    fontSize: 11,
    fontWeight: '700' as const,
  },
  queueStrip: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: Colors.cardBackground,
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: Colors.border,
    marginBottom: 16,
  },
  queueStripTitle: {
    color: Colors.textSecondary,
    fontSize: 12,
    fontWeight: '600' as const,
  },
  queueStripCounts: {
    flexDirection: 'row',
    gap: 8,
  },
  queueBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 10,
  },
  queueBadgePending: {
    backgroundColor: '#FFF3E0',
  },
  queueBadgeCompleted: {
    backgroundColor: '#E8F5E9',
  },
  queueBadgeUncertain: {
    backgroundColor: 'rgba(232,105,45,0.15)',
  },
  queueBadgeRetryable: {
    backgroundColor: '#E3F2FD',
  },
  queueBadgeFailed: {
    backgroundColor: '#FFEBEE',
  },
  queueBadgeText: {
    fontSize: 12,
    fontWeight: '700' as const,
    color: Colors.textPrimary,
  },
  queueBadgeLabel: {
    fontSize: 10,
    color: Colors.textSecondary,
  },
  // --- Image Pre-processing & QR sections ---
  settingsSection: {
    backgroundColor: Colors.cardBackground,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: Colors.border,
    marginBottom: 16,
    gap: 14,
  },
  settingsSectionTitle: {
    color: Colors.gold,
    fontSize: 12,
    fontWeight: '700' as const,
    letterSpacing: 0.6,
    textTransform: 'uppercase' as const,
    marginBottom: 2,
  },
  settingsRow: {
    gap: 8,
  },
  settingsLabel: {
    color: Colors.textPrimary,
    fontSize: 13,
    fontWeight: '600' as const,
  },
  settingsLabelDimmed: {
    color: Colors.textMuted,
  },
  sliderLabelRow: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
  },
  sliderValue: {
    color: Colors.textSecondary,
    fontSize: 12,
    fontWeight: '600' as const,
    minWidth: 44,
    textAlign: 'right' as const,
  },
  stepperRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 10,
  },
  stepperButton: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: Colors.cardBackgroundLight,
    borderWidth: 1,
    borderColor: Colors.borderLight,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
  },
  stepperButtonPressed: {
    opacity: 0.7,
  },
  stepperButtonText: {
    color: Colors.textPrimary,
    fontSize: 18,
    lineHeight: 20,
    fontWeight: '500' as const,
  },
  stepperTrack: {
    flex: 1,
    height: 6,
    borderRadius: 3,
    backgroundColor: Colors.cardBackgroundLight,
    overflow: 'hidden' as const,
  },
  stepperFill: {
    height: '100%' as const,
    borderRadius: 3,
    backgroundColor: Colors.gold,
  },
  chipGroup: {
    flexDirection: 'row' as const,
    flexWrap: 'wrap' as const,
    gap: 6,
  },
  chip: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
    backgroundColor: Colors.cardBackgroundLight,
    borderWidth: 1,
    borderColor: Colors.borderLight,
  },
  chipActive: {
    backgroundColor: 'rgba(232,105,45,0.15)',
    borderColor: Colors.gold,
  },
  chipPressed: {
    opacity: 0.75,
  },
  chipText: {
    color: Colors.textSecondary,
    fontSize: 12,
    fontWeight: '600' as const,
  },
  chipTextActive: {
    color: Colors.gold,
  },
  previewFrame: {
    alignSelf: 'center' as const,
    borderRadius: 10,
    overflow: 'hidden' as const,
    borderWidth: 1,
    borderColor: Colors.borderLight,
    backgroundColor: '#000',
  },
  // ---
  iosFlowCard: {
    backgroundColor: Colors.cardBackground,
    borderRadius: 16,
    padding: 18,
    borderWidth: 1,
    borderColor: 'rgba(91,155,213,0.2)',
    marginBottom: 20,
  },
  iosFlowHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 18,
  },
  iosFlowIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 10,
    backgroundColor: 'rgba(91,155,213,0.12)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  iosFlowTitle: {
    color: Colors.textPrimary,
    fontSize: 16,
    fontWeight: '700' as const,
  },
  stepsContainer: {
    marginBottom: 18,
  },
  stepRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  stepNumber: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: 'rgba(91,155,213,0.15)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  stepNumberText: {
    color: '#5B9BD5',
    fontSize: 13,
    fontWeight: '700' as const,
  },
  stepContent: {
    flex: 1,
    paddingTop: 2,
  },
  stepTitle: {
    color: Colors.textPrimary,
    fontSize: 14,
    fontWeight: '600' as const,
    marginBottom: 2,
  },
  stepDesc: {
    color: Colors.textSecondary,
    fontSize: 12,
    lineHeight: 17,
  },
  openSettingsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#5B9BD5',
    paddingVertical: 12,
    borderRadius: 12,
  },
  openSettingsButtonPressed: {
    opacity: 0.8,
  },
  openSettingsText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600' as const,
  },
  infoCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    backgroundColor: 'rgba(91,155,213,0.06)',
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: 'rgba(91,155,213,0.12)',
    marginBottom: 20,
  },
  infoText: {
    color: Colors.textSecondary,
    fontSize: 13,
    flex: 1,
    lineHeight: 19,
  },
  scanSection: {
    marginBottom: 16,
  },
  scanButtonsRow: {
    flexDirection: 'row',
    gap: 10,
  },
  scanButton: {
    flex: 1,
    backgroundColor: Colors.cardBackground,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(232,105,45,0.25)',
    paddingVertical: 14,
  },
  scanButtonScanning: {
    borderColor: Colors.gold,
    backgroundColor: 'rgba(232,105,45,0.05)',
  },
  scanButtonDisabled: {
    opacity: 0.5,
  },
  scanButtonPressed: {
    backgroundColor: 'rgba(232,105,45,0.08)',
  },
  scanButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  scanButtonText: {
    color: Colors.gold,
    fontSize: 15,
    fontWeight: '600' as const,
  },
  tcpScanButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: Colors.cardBackground,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(232,105,45,0.25)',
    paddingVertical: 14,
    paddingHorizontal: 18,
  },
  tcpScanButtonPressed: {
    backgroundColor: 'rgba(232,105,45,0.08)',
  },
  tcpScanButtonText: {
    color: Colors.gold,
    fontSize: 15,
    fontWeight: '600' as const,
  },
  devicesSection: {
    marginBottom: 16,
  },
  sectionLabel: {
    color: Colors.textMuted,
    fontSize: 11,
    fontWeight: '600' as const,
    letterSpacing: 1.5,
    marginBottom: 8,
    marginLeft: 2,
  },
  deviceItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.cardBackground,
    borderRadius: 12,
    padding: 12,
    marginBottom: 6,
    gap: 10,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  deviceItemConnected: {
    borderColor: 'rgba(34,204,102,0.3)',
    backgroundColor: 'rgba(34,204,102,0.04)',
  },
  deviceIcon: {
    width: 36,
    height: 36,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  deviceIconBle: {
    backgroundColor: 'rgba(91,155,213,0.1)',
  },
  deviceIconClassic: {
    backgroundColor: 'rgba(192,132,252,0.1)',
  },
  deviceIconTcp: {
    backgroundColor: 'rgba(232,105,45,0.1)',
  },
  deviceInfo: {
    flex: 1,
    gap: 3,
  },
  deviceTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  deviceName: {
    color: Colors.textPrimary,
    fontSize: 14,
    fontWeight: '600' as const,
  },
  deviceNameConnected: {
    color: Colors.success,
  },
  deviceMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  typeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    paddingHorizontal: 5,
    paddingVertical: 1,
    borderRadius: 3,
  },
  typeBadgeBle: {
    backgroundColor: 'rgba(91,155,213,0.15)',
  },
  typeBadgeClassic: {
    backgroundColor: 'rgba(192,132,252,0.15)',
  },
  typeBadgeTcp: {
    backgroundColor: 'rgba(232,105,45,0.15)',
  },
  typeBadgeText: {
    fontSize: 9,
    fontWeight: '700' as const,
    letterSpacing: 0.5,
  },
  typeBadgeTextBle: {
    color: '#5B9BD5',
  },
  typeBadgeTextClassic: {
    color: '#C084FC',
  },
  typeBadgeTextTcp: {
    color: Colors.gold,
  },
  deviceAddress: {
    color: Colors.textMuted,
    fontSize: 10,
  },
  preferredChip: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    backgroundColor: 'rgba(232,105,45,0.12)',
  },
  preferredChipText: {
    color: Colors.gold,
    fontSize: 10,
    fontWeight: '700' as const,
  },
  deviceActions: {
    alignItems: 'flex-end',
    gap: 6,
  },
  deviceActionButton: {
    minWidth: 80,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 10,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  deviceActionPrimary: {
    backgroundColor: Colors.gold,
    borderColor: Colors.goldDark,
  },
  deviceActionSecondary: {
    backgroundColor: 'rgba(232,105,45,0.08)',
    borderColor: 'rgba(232,105,45,0.2)',
  },
  deviceActionDisabled: {
    opacity: 0.7,
  },
  deviceActionPressed: {
    opacity: 0.85,
  },
  deviceActionPrimaryText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '700' as const,
  },
  deviceActionSecondaryText: {
    color: Colors.gold,
    fontSize: 11,
    fontWeight: '700' as const,
  },
  deviceActionIcon: {
    padding: 6,
    borderRadius: 6,
  },
  deviceActionIconPressed: {
    backgroundColor: 'rgba(239,83,80,0.08)',
  },
  connectedCheck: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: Colors.success,
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyState: {
    alignItems: 'center',
    paddingTop: 48,
    gap: 10,
  },
  emptyTitle: {
    color: Colors.textPrimary,
    fontSize: 17,
    fontWeight: '600' as const,
  },
  emptySubtitle: {
    color: Colors.textSecondary,
    fontSize: 13,
    textAlign: 'center' as const,
    lineHeight: 19,
    paddingHorizontal: 24,
  },
  compatRow: {
    flexDirection: 'row',
    gap: 16,
    marginTop: 14,
  },
  compatItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: Colors.cardBackground,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  compatText: {
    color: Colors.textSecondary,
    fontSize: 11,
    fontWeight: '500' as const,
  },
  tcpModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'flex-end',
  },
  tcpModalContent: {
    backgroundColor: Colors.cardBackground,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    paddingBottom: 40,
  },
  tcpModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  tcpModalTitle: {
    fontSize: 18,
    fontWeight: '700' as const,
    color: Colors.textPrimary,
  },
  tcpModalClose: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: Colors.inputBackground,
    justifyContent: 'center',
    alignItems: 'center',
  },
  tcpModalDesc: {
    fontSize: 13,
    color: Colors.textSecondary,
    lineHeight: 18,
    marginBottom: 20,
  },
  tcpFormField: {
    marginBottom: 16,
  },
  tcpFormLabel: {
    fontSize: 12,
    fontWeight: '600' as const,
    color: Colors.textSecondary,
    marginBottom: 6,
    letterSpacing: 0.5,
  },
  tcpFormInput: {
    backgroundColor: Colors.inputBackground,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.border,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    color: Colors.textPrimary,
  },
  tcpAddButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: Colors.gold,
    paddingVertical: 14,
    borderRadius: 12,
    marginTop: 4,
  },
  tcpAddButtonPressed: {
    opacity: 0.85,
  },
  tcpAddButtonDisabled: {
    opacity: 0.6,
  },
  tcpAddButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700' as const,
  },
});
