export {
  PrinterEventType,
  initPrinterDiagnostics,
  setPrinterSessionLogger,
  getPrinterSessionLogger,
  consolePrinterLogger,
  noOpPrinterLogger,
  emitPermissionRequested,
  emitPermissionGranted,
  emitPermissionDenied,
  emitDiscoveryStarted,
  emitDiscoveryResult,
  emitDiscoveryCompleted,
  emitConnectStarted,
  emitConnectSuccess,
  emitConnectFailed,
  emitDisconnected,
  emitJobQueued,
  emitJobDispatched,
  emitJobCompleted,
  emitJobFailed,
  emitJobSentUnknown,
  emitNativeError,
  type PrinterSessionEvent,
  type PrinterSessionLogger,
} from './logger';
